name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run tests
        run: biome lint

  typescript:
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NPM cache
        uses: actions/cache@v4
        env:
          cache-name: npm-cache
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: [18.x, 20.x, 21.x, 22.x, 23.x, 24.x]

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run build

  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run formatting
        run: biome format

  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NPM cache
        uses: actions/cache@v4
        env:
          cache-name: npm-cache
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: [18.x, 20.x, 21.x, 22.x, 23.x, 24.x]

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
